version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "register_employee:1:1, change_department:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  employee_management:
    depends_on:
      - "kafka"
    image: employee_management
    build: ./employee_management
    ports: ['5000:5000']
    volumes: ['./employee_management:/app']
  task_management:
    depends_on:
      - "kafka"
    image: task_management
    build:  ./task_management
    ports: ['5001:5001']
    volumes: ['./task_management:/app']
  statistic_report:
    depends_on:
      - "kafka"
    image: statistic_report
    build:  ./statistic_report
    ports: ['4001:4001']
    volumes: ['./statistic_report:/app']