version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "register_employee:1:1, register_user:1:1,update_passwd:1:1,update_department:1:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  employee_management:
    depends_on:
      - "kafka"
    image: employee_management
    build: ./employee_management
    ports: ['6001:6001']
    volumes: ['./employee_management:/app']
  task_management:
    depends_on:
      - "kafka"
    image: task_management
    build:  ./task_management
    ports: ['6003:6003']
    volumes: ['./task_management:/app']
  user_management:
    depends_on:
      - "kafka"
    image: user_management
    build:  ./user_management
    ports: ['6002:6002']
    volumes: ['./user_management:/app']

